// Winget Apps Data
const wingetApps = [
    { "name": "1Password", "icon": "", "wingetId": "AgileBits.1Password", "category": "Utilities" },
    { "name": "7-Zip", "icon": "", "wingetId": "7zip.7zip", "category": "Utilities" },
    { "name": "Adobe Acrobat Reader", "icon": "", "wingetId": "Adobe.Acrobat.Reader.64-bit", "category": "Document" },
    { "name": "Advanced IP Scanner", "icon": "", "wingetId": "Famatech.AdvancedIPScanner", "category": "Pro Tools" },
    { "name": "AFFiNE", "icon": "", "wingetId": "ToEverything.AFFiNE", "category": "Document" },
    { "name": "AIMP (Music Player)", "icon": "", "wingetId": "AIMP.AIMP", "category": "Multimedia Tools" },
    { "name": "Alacritty Terminal", "icon": "", "wingetId": "Alacritty.Alacritty", "category": "Utilities" },
    { "name": "Anaconda", "icon": "", "wingetId": "Anaconda.Anaconda3", "category": "Development" },
    { "name": "Angry IP Scanner", "icon": "", "wingetId": "angryziber.AngryIPScanner", "category": "Pro Tools" },
    { "name": "Anki", "icon": "", "wingetId": "Anki.Anki", "category": "Document" },
    { "name": "AnyDesk", "icon": "", "wingetId": "AnyDeskSoftwareGmbH.AnyDesk", "category": "Utilities" },
    { "name": "Audacity", "icon": "", "wingetId": "Audacity.Audacity", "category": "Multimedia Tools" },
    { "name": "Autoruns", "icon": "", "wingetId": "Microsoft.Sysinternals.Autoruns", "category": "Microsoft Tools" },
    { "name": "RDCMan", "icon": "", "wingetId": "Microsoft.Sysinternals.RDCMan", "category": "Microsoft Tools" },
    { "name": "AutoHotkey", "icon": "", "wingetId": "AutoHotkey.AutoHotkey", "category": "Utilities" },
    { "name": "Microsoft Azure Data Studio", "icon": "", "wingetId": "Microsoft.AzureDataStudio", "category": "Microsoft Tools" },
    { "name": "Barrier", "icon": "", "wingetId": "DebaucheeOpenSourceGroup.Barrier", "category": "Utilities" },
    { "name": "Bat (Cat)", "icon": "", "wingetId": "sharkdp.bat", "category": "Utilities" },
    { "name": "Bitwarden", "icon": "", "wingetId": "Bitwarden.Bitwarden", "category": "Utilities" },
    { "name": "BleachBit", "icon": "", "wingetId": "BleachBit.BleachBit", "category": "Utilities" },
    { "name": "Blender (3D Graphics)", "icon": "", "wingetId": "BlenderFoundation.Blender", "category": "Multimedia Tools" },
    { "name": "Brave", "icon": "", "wingetId": "Brave.Brave", "category": "Browsers" },
    { "name": "Bulk Crap Uninstaller", "icon": "", "wingetId": "Klocman.BulkCrapUninstaller", "category": "Utilities" },
    { "name": "Bulk Rename Utility", "icon": "", "wingetId": "TGRMNSoftware.BulkRenameUtility", "category": "Utilities" },
    { "name": "Advanced Renamer", "icon": "", "wingetId": "HulubuluSoftware.AdvancedRenamer", "category": "Utilities" },
    { "name": "Calibre", "icon": "", "wingetId": "calibre.calibre", "category": "Document" },
    { "name": "Carnac", "icon": "", "wingetId": "code52.Carnac", "category": "Utilities" },
    { "name": "Cemu", "icon": "", "wingetId": "Cemu.Cemu", "category": "Games" },
    { "name": "Chatterino", "icon": "", "wingetId": "ChatterinoTeam.Chatterino", "category": "Communications" },
    { "name": "Chrome", "icon": "", "wingetId": "Google.Chrome", "category": "Browsers" },
    { "name": "Chromium", "icon": "", "wingetId": "Hibbiki.Chromium", "category": "Browsers" },
    { "name": "Arc", "icon": "", "wingetId": "TheBrowserCompany.Arc", "category": "Browsers" },
    { "name": "Clementine", "icon": "", "wingetId": "Clementine.Clementine", "category": "Multimedia Tools" },
    { "name": "Clink", "icon": "", "wingetId": "chrisant996.Clink", "category": "Development" },
    { "name": "Clone Hero", "icon": "", "wingetId": "CloneHeroTeam.CloneHero", "category": "Games" },
    { "name": "CMake", "icon": "", "wingetId": "Kitware.CMake", "category": "Development" },
    { "name": "CopyQ (Clipboard Manager)", "icon": "", "wingetId": "hluk.CopyQ", "category": "Utilities" },
    { "name": "CPU-Z", "icon": "", "wingetId": "CPUID.CPU-Z", "category": "Utilities" },
    { "name": "Crystal Disk Info", "icon": "", "wingetId": "CrystalDewWorld.CrystalDiskInfo", "category": "Utilities" },
    { "name": "CapFrameX", "icon": "", "wingetId": "CXWorld.CapFrameX", "category": "Utilities" },
    { "name": "Crystal Disk Mark", "icon": "", "wingetId": "CrystalDewWorld.CrystalDiskMark", "category": "Utilities" },
    { "name": "darktable", "icon": "", "wingetId": "darktable.darktable", "category": "Multimedia Tools" },
    { "name": "DaxStudio", "icon": "", "wingetId": "DaxStudio.DaxStudio", "category": "Development" },
    { "name": "Display Driver Uninstaller", "icon": "", "wingetId": "Wagnardsoft.DisplayDriverUninstaller", "category": "Utilities" },
    { "name": "Deluge", "icon": "", "wingetId": "DelugeTeam.Deluge", "category": "Utilities" },
    { "name": "DevToys", "icon": "", "wingetId": "DevToys-app.DevToys", "category": "Utilities" },
    { "name": "digiKam", "icon": "", "wingetId": "KDE.digikam", "category": "Multimedia Tools" },
    { "name": "Discord", "icon": "", "wingetId": "Discord.Discord", "category": "Communications" },
    { "name": "Ditto", "icon": "", "wingetId": "Ditto.Ditto", "category": "Utilities" },
    { "name": "Docker Desktop", "icon": "", "wingetId": "Docker.DockerDesktop", "category": "Development" },
    { "name": ".NET Desktop Runtime 3.1", "icon": "", "wingetId": "Microsoft.DotNet.DesktopRuntime.3_1", "category": "Microsoft Tools" },
    { "name": ".NET Desktop Runtime 5", "icon": "", "wingetId": "Microsoft.DotNet.DesktopRuntime.5", "category": "Microsoft Tools" },
    { "name": ".NET Desktop Runtime 6", "icon": "", "wingetId": "Microsoft.DotNet.DesktopRuntime.6", "category": "Microsoft Tools" },
    { "name": ".NET Desktop Runtime 7", "icon": "", "wingetId": "Microsoft.DotNet.DesktopRuntime.7", "category": "Microsoft Tools" },
    { "name": ".NET Desktop Runtime 8", "icon": "", "wingetId": "Microsoft.DotNet.DesktopRuntime.8", "category": "Microsoft Tools" },
    { "name": ".NET Desktop Runtime 9", "icon": "", "wingetId": "Microsoft.DotNet.DesktopRuntime.9", "category": "Microsoft Tools" },
    { "name": "Dual Monitor Tools", "icon": "", "wingetId": "GNE.DualMonitorTools", "category": "Utilities" },
    { "name": "Duplicati", "icon": "", "wingetId": "Duplicati.Duplicati", "category": "Utilities" },
    { "name": "EA App", "icon": "", "wingetId": "ElectronicArts.EADesktop", "category": "Games" },
    { "name": "EarTrumpet (Audio)", "icon": "", "wingetId": "File-New-Project.EarTrumpet", "category": "Multimedia Tools" },
    { "name": "Edge", "icon": "", "wingetId": "Microsoft.Edge", "category": "Browsers" },
    { "name": "EFI Boot Editor", "icon": "", "wingetId": "EFIBootEditor.EFIBootEditor", "category": "Pro Tools" },
    { "name": "Emulation Station", "icon": "", "wingetId": "Emulationstation.Emulationstation", "category": "Games" },
    { "name": "Epic Games Launcher", "icon": "", "wingetId": "EpicGames.EpicGamesLauncher", "category": "Games" },
    { "name": "Everything Search", "icon": "", "wingetId": "voidtools.Everything", "category": "Utilities" },
    { "name": "Espanso", "icon": "", "wingetId": "Espanso.Espanso", "category": "Utilities" },
    { "name": "Falkon", "icon": "", "wingetId": "KDE.Falkon", "category": "Browsers" },
    { "name": "Fastfetch", "icon": "", "wingetId": "Fastfetch-cli.Fastfetch", "category": "Utilities" },
    { "name": "Ferdium", "icon": "", "wingetId": "Ferdium.Ferdium", "category": "Communications" },
    { "name": "FFmpeg (full)", "icon": "", "wingetId": "Gyan.FFmpeg", "category": "Multimedia Tools" },
    { "name": "File-Converter", "icon": "", "wingetId": "AdrienAllard.FileConverter", "category": "Utilities" },
    { "name": "Files", "icon": "", "wingetId": "na", "category": "Utilities" },
    { "name": "Fire Alpaca", "icon": "", "wingetId": "FireAlpaca.FireAlpaca", "category": "Multimedia Tools" },
    { "name": "Firefox", "icon": "", "wingetId": "Mozilla.Firefox", "category": "Browsers" },
    { "name": "Firefox ESR", "icon": "", "wingetId": "Mozilla.Firefox.ESR", "category": "Browsers" },
    { "name": "Flameshot (Screenshots)", "icon": "", "wingetId": "Flameshot.Flameshot", "category": "Multimedia Tools" },
    { "name": "Lightshot (Screenshots)", "icon": "", "wingetId": "Skillbrains.Lightshot", "category": "Multimedia Tools" },
    { "name": "Floorp", "icon": "", "wingetId": "Ablaze.Floorp", "category": "Browsers" },
    { "name": "Flow launcher", "icon": "", "wingetId": "Flow-Launcher.Flow-Launcher", "category": "Utilities" },
    { "name": "F.lux", "icon": "", "wingetId": "flux.flux", "category": "Utilities" },
    { "name": "foobar2000 (Music Player)", "icon": "", "wingetId": "PeterPawlowski.foobar2000", "category": "Multimedia Tools" },
    { "name": "Foxit PDF Editor", "icon": "", "wingetId": "Foxit.PhantomPDF", "category": "Document" },
    { "name": "Foxit PDF Reader", "icon": "", "wingetId": "Foxit.FoxitReader", "category": "Document" },
    { "name": "FreeCAD", "icon": "", "wingetId": "FreeCAD.FreeCAD", "category": "Multimedia Tools" },
    { "name": "FxSound", "icon": "", "wingetId": "FxSound.FxSound", "category": "Multimedia Tools" },
    { "name": "Fzf", "icon": "", "wingetId": "junegunn.fzf", "category": "Utilities" },
    { "name": "GeForce NOW", "icon": "", "wingetId": "Nvidia.GeForceNow", "category": "Games" },
    { "name": "GIMP (Image Editor)", "icon": "", "wingetId": "GIMP.GIMP.3", "category": "Multimedia Tools" },
    { "name": "Git", "icon": "", "wingetId": "Git.Git", "category": "Development" },
    { "name": "Git Butler", "icon": "", "wingetId": "GitButler.GitButler", "category": "Development" },
    { "name": "Git Extensions", "icon": "", "wingetId": "GitExtensionsTeam.GitExtensions", "category": "Development" },
    { "name": "GitHub CLI", "icon": "", "wingetId": "GitHub.cli", "category": "Development" },
    { "name": "GitHub Desktop", "icon": "", "wingetId": "GitHub.GitHubDesktop", "category": "Development" },
    { "name": "GitKraken Client", "icon": "", "wingetId": "Axosoft.GitKraken", "category": "Development" },
    { "name": "Glary Utilities", "icon": "", "wingetId": "Glarysoft.GlaryUtilities", "category": "Utilities" },
    { "name": "Godot Engine", "icon": "", "wingetId": "GodotEngine.GodotEngine", "category": "Development" },
    { "name": "GOG Galaxy", "icon": "", "wingetId": "GOG.Galaxy", "category": "Games" },
    { "name": "Gitify", "icon": "", "wingetId": "Gitify.Gitify", "category": "Development" },
    { "name": "Go", "icon": "", "wingetId": "GoLang.Go", "category": "Development" },
    { "name": "Google Drive", "icon": "", "wingetId": "Google.GoogleDrive", "category": "Utilities" },
    { "name": "GPU-Z", "icon": "", "wingetId": "TechPowerUp.GPU-Z", "category": "Utilities" },
    { "name": "Greenshot (Screenshots)", "icon": "", "wingetId": "Greenshot.Greenshot", "category": "Multimedia Tools" },
    { "name": "Gsudo", "icon": "", "wingetId": "gerardog.gsudo", "category": "Utilities" },
    { "name": "Guilded", "icon": "", "wingetId": "Guilded.Guilded", "category": "Communications" },
    { "name": "HandBrake", "icon": "", "wingetId": "HandBrake.HandBrake", "category": "Multimedia Tools" },
    { "name": "Harmonoid", "icon": "", "wingetId": "Harmonoid.Harmonoid", "category": "Multimedia Tools" },
    { "name": "HeidiSQL", "icon": "", "wingetId": "HeidiSQL.HeidiSQL", "category": "Pro Tools" },
    { "name": "Helix", "icon": "", "wingetId": "Helix.Helix", "category": "Development" },
    { "name": "Heroic Games Launcher", "icon": "", "wingetId": "HeroicGamesLauncher.HeroicGamesLauncher", "category": "Games" },
    { "name": "Hexchat", "icon": "", "wingetId": "HexChat.HexChat", "category": "Communications" },
    { "name": "HWiNFO", "icon": "", "wingetId": "REALiX.HWiNFO", "category": "Utilities" },
    { "name": "HWMonitor", "icon": "", "wingetId": "CPUID.HWMonitor", "category": "Utilities" },
    { "name": "ImageGlass (Image Viewer)", "icon": "", "wingetId": "DuongDieuPhap.ImageGlass", "category": "Multimedia Tools" },
    { "name": "ImgBurn", "icon": "", "wingetId": "LIGHTNINGUK.ImgBurn", "category": "Multimedia Tools" },
    { "name": "Inkscape", "icon": "", "wingetId": "Inkscape.Inkscape", "category": "Multimedia Tools" },
    { "name": "Itch.io", "icon": "", "wingetId": "ItchIo.Itch", "category": "Games" },
    { "name": "iTunes", "icon": "", "wingetId": "Apple.iTunes", "category": "Multimedia Tools" },
    { "name": "Jami", "icon": "", "wingetId": "SFLinux.Jami", "category": "Communications" },
    { "name": "Amazon Corretto 8 (LTS)", "icon": "", "wingetId": "Amazon.Corretto.8.JDK", "category": "Development" },
    { "name": "Amazon Corretto 11 (LTS)", "icon": "", "wingetId": "Amazon.Corretto.11.JDK", "category": "Development" },
    { "name": "Amazon Corretto 17 (LTS)", "icon": "", "wingetId": "Amazon.Corretto.17.JDK", "category": "Development" },
    { "name": "Amazon Corretto 21 (LTS)", "icon": "", "wingetId": "Amazon.Corretto.21.JDK", "category": "Development" },
    { "name": "JDownloader", "icon": "", "wingetId": "AppWork.JDownloader", "category": "Utilities" },
    { "name": "Jellyfin Media Player", "icon": "", "wingetId": "Jellyfin.JellyfinMediaPlayer", "category": "Multimedia Tools" },
    { "name": "Jellyfin Server", "icon": "", "wingetId": "Jellyfin.Server", "category": "Multimedia Tools" },
    { "name": "Jetbrains Toolbox", "icon": "", "wingetId": "JetBrains.Toolbox", "category": "Development" },
    { "name": "Joplin (FOSS Notes)", "icon": "", "wingetId": "Joplin.Joplin", "category": "Document" },
    { "name": "JPEG View", "icon": "", "wingetId": "sylikc.JPEGView", "category": "Utilities" },
    { "name": "KDE Connect", "icon": "", "wingetId": "KDE.KDEConnect", "category": "Utilities" },
    { "name": "Kdenlive (Video Editor)", "icon": "", "wingetId": "KDE.Kdenlive", "category": "Multimedia Tools" },
    { "name": "KeePassXC", "icon": "", "wingetId": "KeePassXCTeam.KeePassXC", "category": "Utilities" },
    { "name": "K-Lite Codec Standard", "icon": "", "wingetId": "CodecGuide.K-LiteCodecPack.Standard", "category": "Multimedia Tools" },
    { "name": "Kodi Media Center", "icon": "", "wingetId": "XBMCFoundation.Kodi", "category": "Multimedia Tools" },
    { "name": "Krita (Image Editor)", "icon": "", "wingetId": "KDE.Krita", "category": "Multimedia Tools" },
    { "name": "Lazygit", "icon": "", "wingetId": "JesseDuffield.lazygit", "category": "Development" },
    { "name": "LibreOffice", "icon": "", "wingetId": "TheDocumentFoundation.LibreOffice", "category": "Document" },
    { "name": "LibreWolf", "icon": "", "wingetId": "LibreWolf.LibreWolf", "category": "Browsers" },
    { "name": "Link Shell extension", "icon": "", "wingetId": "HermannSchinagl.LinkShellExtension", "category": "Utilities" },
    { "name": "Linphone", "icon": "", "wingetId": "BelledonneCommunications.Linphone", "category": "Communications" },
    { "name": "Lively Wallpaper", "icon": "", "wingetId": "rocksdanister.LivelyWallpaper", "category": "Utilities" },
    { "name": "LocalSend", "icon": "", "wingetId": "LocalSend.LocalSend", "category": "Utilities" },
    { "name": "LockHunter", "icon": "", "wingetId": "CrystalRich.LockHunter", "category": "Utilities" },
    { "name": "Logseq", "icon": "", "wingetId": "Logseq.Logseq", "category": "Document" },
    { "name": "Malwarebytes", "icon": "", "wingetId": "Malwarebytes.Malwarebytes", "category": "Utilities" },
    { "name": "massCode (Snippet Manager)", "icon": "", "wingetId": "antonreshetov.massCode", "category": "Document" },
    { "name": "Element", "icon": "", "wingetId": "Element.Element", "category": "Communications" },
    { "name": "Meld", "icon": "", "wingetId": "Meld.Meld", "category": "Utilities" },
    { "name": "Modern Flyouts", "icon": "", "wingetId": "ModernFlyouts.ModernFlyouts", "category": "Multimedia Tools" },
    { "name": "Monitorian", "icon": "", "wingetId": "emoacht.Monitorian", "category": "Utilities" },
    { "name": "Moonlight/GameStream Client", "icon": "", "wingetId": "MoonlightGameStreamingProject.Moonlight", "category": "Games" },
    { "name": "Motrix Download Manager", "icon": "", "wingetId": "agalwood.Motrix", "category": "Utilities" },
    { "name": "Media Player Classic - Home Cinema", "icon": "", "wingetId": "clsid2.mpc-hc", "category": "Multimedia Tools" },
    { "name": "mRemoteNG", "icon": "", "wingetId": "mRemoteNG.mRemoteNG", "category": "Pro Tools" },
    { "name": "MSEdgeRedirect", "icon": "", "wingetId": "rcmaehl.MSEdgeRedirect", "category": "Utilities" },
    { "name": "MSI Afterburner", "icon": "", "wingetId": "Guru3D.Afterburner", "category": "Utilities" },
    { "name": "Mullvad VPN", "icon": "", "wingetId": "MullvadVPN.MullvadVPN", "category": "Pro Tools" },
    { "name": "Borderless Gaming", "icon": "", "wingetId": "Codeusa.BorderlessGaming", "category": "Utilities" },
    { "name": "Equalizer APO", "icon": "", "wingetId": "na", "category": "Multimedia Tools" },
    { "name": "Compact GUI", "icon": "", "wingetId": "IridiumIO.CompactGUI", "category": "Utilities" },
    { "name": "ExifCleaner", "icon": "", "wingetId": "szTheory.exifcleaner", "category": "Utilities" },
    { "name": "Mullvad Browser", "icon": "", "wingetId": "MullvadVPN.MullvadBrowser", "category": "Browsers" },
    { "name": "MuseScore", "icon": "", "wingetId": "Musescore.Musescore", "category": "Multimedia Tools" },
    { "name": "MusicBee (Music Player)", "icon": "", "wingetId": "MusicBee.MusicBee", "category": "Multimedia Tools" },
    { "name": "Mp3tag (Metadata Audio Editor)", "icon": "", "wingetId": "Mp3tag.Mp3tag", "category": "Multimedia Tools" },
    { "name": "TagScanner (Tag Scanner)", "icon": "", "wingetId": "SergeySerkov.TagScanner", "category": "Multimedia Tools" },
    { "name": "NanaZip", "icon": "", "wingetId": "M2Team.NanaZip", "category": "Utilities" },
    { "name": "NetBird", "icon": "", "wingetId": "netbird", "category": "Pro Tools" },
    { "name": "NAPS2 (Document Scanner)", "icon": "", "wingetId": "Cyanfish.NAPS2", "category": "Document" },
    { "name": "Neofetch", "icon": "", "wingetId": "nepnep.neofetch-win", "category": "Utilities" },
    { "name": "Neovim", "icon": "", "wingetId": "Neovim.Neovim", "category": "Development" },
    { "name": "Nextcloud Desktop", "icon": "", "wingetId": "Nextcloud.NextcloudDesktop", "category": "Utilities" },
    { "name": "nGlide (3dfx compatibility)", "icon": "", "wingetId": "ZeusSoftware.nGlide", "category": "Multimedia Tools" },
    { "name": "Nmap", "icon": "", "wingetId": "Insecure.Nmap", "category": "Pro Tools" },
    { "name": "NodeJS", "icon": "", "wingetId": "OpenJS.NodeJS", "category": "Development" },
    { "name": "NodeJS LTS", "icon": "", "wingetId": "OpenJS.NodeJS.LTS", "category": "Development" },
    { "name": "Nomacs (Image viewer)", "icon": "", "wingetId": "nomacs.nomacs", "category": "Multimedia Tools" },
    { "name": "Notepad++", "icon": "", "wingetId": "Notepad++.Notepad++", "category": "Document" },
    { "name": "NuGet", "icon": "", "wingetId": "Microsoft.NuGet", "category": "Microsoft Tools" },
    { "name": "Nushell", "icon": "", "wingetId": "Nushell.Nushell", "category": "Utilities" },
    { "name": "NVCleanstall", "icon": "", "wingetId": "TechPowerUp.NVCleanstall", "category": "Utilities" },
    { "name": "Node Version Manager", "icon": "", "wingetId": "CoreyButler.NVMforWindows", "category": "Development" },
    { "name": "OBS Studio", "icon": "", "wingetId": "OBSProject.OBSStudio", "category": "Multimedia Tools" },
    { "name": "Obsidian", "icon": "", "wingetId": "Obsidian.Obsidian", "category": "Document" },
    { "name": "Okular", "icon": "", "wingetId": "KDE.Okular", "category": "Document" },
    { "name": "OneDrive", "icon": "", "wingetId": "Microsoft.OneDrive", "category": "Microsoft Tools" },
    { "name": "ONLYOffice Desktop", "icon": "", "wingetId": "ONLYOFFICE.DesktopEditors", "category": "Document" },
    { "name": "OPAutoClicker", "icon": "", "wingetId": "OPAutoClicker.OPAutoClicker", "category": "Utilities" },
    { "name": "OpenHashTab", "icon": "", "wingetId": "namazso.OpenHashTab", "category": "Utilities" },
    { "name": "OpenRGB", "icon": "", "wingetId": "CalcProgrammer1.OpenRGB", "category": "Utilities" },
    { "name": "OpenSCAD", "icon": "", "wingetId": "OpenSCAD.OpenSCAD", "category": "Multimedia Tools" },
    { "name": "Open Shell (Start Menu)", "icon": "", "wingetId": "Open-Shell.Open-Shell-Menu", "category": "Utilities" },
    { "name": "OpenVPN Connect", "icon": "", "wingetId": "OpenVPNTechnologies.OpenVPNConnect", "category": "Pro Tools" },
    { "name": "Oracle VirtualBox", "icon": "", "wingetId": "Oracle.VirtualBox", "category": "Utilities" },
    { "name": "ownCloud Desktop", "icon": "", "wingetId": "ownCloud.ownCloudDesktop", "category": "Utilities" },
    { "name": "Paint.NET", "icon": "", "wingetId": "dotPDN.PaintDotNet", "category": "Multimedia Tools" },
    { "name": "Parsec", "icon": "", "wingetId": "Parsec.Parsec", "category": "Utilities" },
    { "name": "PDF24 creator", "icon": "", "wingetId": "geeksoftwareGmbH.PDF24Creator", "category": "Document" },
    { "name": "PDFsam Basic", "icon": "", "wingetId": "PDFsam.PDFsam", "category": "Document" },
    { "name": "PeaZip", "icon": "", "wingetId": "Giorgiotani.Peazip", "category": "Utilities" },
    { "name": "Raspberry Pi Imager", "icon": "", "wingetId": "RaspberryPiFoundation.RaspberryPiImager", "category": "Utilities" },
    { "name": "Playnite", "icon": "", "wingetId": "Playnite.Playnite", "category": "Games" },
    { "name": "Plex Media Server", "icon": "", "wingetId": "Plex.PlexMediaServer", "category": "Multimedia Tools" },
    { "name": "Plex Desktop", "icon": "", "wingetId": "Plex.Plex", "category": "Multimedia Tools" },
    { "name": "Portmaster", "icon": "", "wingetId": "Safing.Portmaster", "category": "Pro Tools" },
    { "name": "Oh My Posh (Prompt)", "icon": "", "wingetId": "JanDeDobbeleer.OhMyPosh", "category": "Development" },
    { "name": "Postman", "icon": "", "wingetId": "Postman.Postman", "category": "Development" },
    { "name": "Power Automate", "icon": "", "wingetId": "Microsoft.PowerAutomateDesktop", "category": "Microsoft Tools" },
    { "name": "Power BI", "icon": "", "wingetId": "Microsoft.PowerBI", "category": "Microsoft Tools" },
    { "name": "PowerShell", "icon": "", "wingetId": "Microsoft.PowerShell", "category": "Microsoft Tools" },
    { "name": "PowerToys", "icon": "", "wingetId": "Microsoft.PowerToys", "category": "Microsoft Tools" },
    { "name": "Prism Launcher", "icon": "", "wingetId": "PrismLauncher.PrismLauncher", "category": "Games" },
    { "name": "Process Lasso", "icon": "", "wingetId": "BitSum.ProcessLasso", "category": "Utilities" },
    { "name": "Spotify", "icon": "", "wingetId": "Spotify.Spotify", "category": "Multimedia Tools" },
    { "name": "SysInternals Process Monitor", "icon": "", "wingetId": "Microsoft.Sysinternals.ProcessMonitor", "category": "Microsoft Tools" },
    { "name": "OrcaSlicer", "icon": "", "wingetId": "SoftFever.OrcaSlicer", "category": "Utilities" },
    { "name": "PrusaSlicer", "icon": "", "wingetId": "Prusa3d.PrusaSlicer", "category": "Utilities" },
    { "name": "PS Remote Play", "icon": "", "wingetId": "PlayStation.PSRemotePlay", "category": "Games" },
    { "name": "PuTTY", "icon": "", "wingetId": "PuTTY.PuTTY", "category": "Pro Tools" },
    { "name": "Python3", "icon": "", "wingetId": "Python.Python.3.12", "category": "Development" },
    { "name": "qBittorrent", "icon": "", "wingetId": "qBittorrent.qBittorrent", "category": "Utilities" },
    { "name": "Transmission", "icon": "", "wingetId": "Transmission.Transmission", "category": "Utilities" },
    { "name": "Tixati", "icon": "", "wingetId": "Tixati.Tixati.Portable", "category": "Utilities" },
    { "name": "QTox", "icon": "", "wingetId": "Tox.qTox", "category": "Communications" },
    { "name": "Quicklook", "icon": "", "wingetId": "QL-Win.QuickLook", "category": "Utilities" },
    { "name": "Rainmeter", "icon": "", "wingetId": "Rainmeter.Rainmeter", "category": "Utilities" },
    { "name": "Revo Uninstaller", "icon": "", "wingetId": "RevoUninstaller.RevoUninstaller", "category": "Utilities" },
    { "name": "Wise Program Uninstaller (WiseCleaner)", "icon": "", "wingetId": "WiseCleaner.WiseProgramUninstaller", "category": "Utilities" },
    { "name": "Revolt", "icon": "", "wingetId": "Revolt.RevoltDesktop", "category": "Communications" },
    { "name": "Ripgrep", "icon": "", "wingetId": "BurntSushi.ripgrep.MSVC", "category": "Utilities" },
    { "name": "Rufus Imager", "icon": "", "wingetId": "Rufus.Rufus", "category": "Utilities" },
    { "name": "RustDesk", "icon": "", "wingetId": "RustDesk.RustDesk", "category": "Pro Tools" },
    { "name": "Rust", "icon": "", "wingetId": "Rustlang.Rust.MSVC", "category": "Development" },
    { "name": "SageThumbs", "icon": "", "wingetId": "CherubicSoftware.SageThumbs", "category": "Utilities" },
    { "name": "Sandboxie Plus", "icon": "", "wingetId": "Sandboxie.Plus", "category": "Utilities" },
    { "name": "Snappy Driver Installer Origin", "icon": "", "wingetId": "GlennDelahoy.SnappyDriverInstallerOrigin", "category": "Utilities" },
    { "name": "Session", "icon": "", "wingetId": "Oxen.Session", "category": "Communications" },
    { "name": "ShareX (Screenshots)", "icon": "", "wingetId": "ShareX.ShareX", "category": "Multimedia Tools" },
    { "name": "Nilesoft Shell", "icon": "", "wingetId": "Nilesoft.Shell", "category": "Utilities" },
    { "name": "SideQuestVR", "icon": "", "wingetId": "SideQuestVR.SideQuest", "category": "Games" },
    { "name": "Signal", "icon": "", "wingetId": "OpenWhisperSystems.Signal", "category": "Communications" },
    { "name": "SignalRGB", "icon": "", "wingetId": "WhirlwindFX.SignalRgb", "category": "Utilities" },
    { "name": "simplenote", "icon": "", "wingetId": "Automattic.Simplenote", "category": "Document" },
    { "name": "Simplewall", "icon": "", "wingetId": "Henry++.simplewall", "category": "Pro Tools" },
    { "name": "Skype", "icon": "", "wingetId": "Microsoft.Skype", "category": "Communications" },
    { "name": "Slack", "icon": "", "wingetId": "SlackTechnologies.Slack", "category": "Communications" },
    { "name": "Spacedrive File Manager", "icon": "", "wingetId": "spacedrive.Spacedrive", "category": "Utilities" },
    { "name": "SpaceSniffer", "icon": "", "wingetId": "UderzoSoftware.SpaceSniffer", "category": "Utilities" },
    { "name": "Starship (Shell Prompt)", "icon": "", "wingetId": "starship", "category": "Development" },
    { "name": "Steam", "icon": "", "wingetId": "Valve.Steam", "category": "Games" },
    { "name": "Strawberry (Music Player)", "icon": "", "wingetId": "StrawberryMusicPlayer.Strawberry", "category": "Multimedia Tools" },
    { "name": "Stremio", "icon": "", "wingetId": "Stremio.Stremio", "category": "Multimedia Tools" },
    { "name": "Sublime Merge", "icon": "", "wingetId": "SublimeHQ.SublimeMerge", "category": "Development" },
    { "name": "Sublime Text", "icon": "", "wingetId": "SublimeHQ.SublimeText.4", "category": "Development" },
    { "name": "Sumatra PDF", "icon": "", "wingetId": "SumatraPDF.SumatraPDF", "category": "Document" },
    { "name": "PDFgear", "icon": "", "wingetId": "PDFgear.PDFgear", "category": "Document" },
    { "name": "Sunshine/GameStream Server", "icon": "", "wingetId": "LizardByte.Sunshine", "category": "Games" },
    { "name": "SuperF4", "icon": "", "wingetId": "StefanSundin.Superf4", "category": "Utilities" },
    { "name": "Swift toolchain", "icon": "", "wingetId": "Swift.Toolchain", "category": "Development" },
    { "name": "SyncTrayzor", "icon": "", "wingetId": "SyncTrayzor.SyncTrayzor", "category": "Utilities" },
    { "name": "Microsoft SQL Server Management Studio", "icon": "", "wingetId": "Microsoft.SQLServerManagementStudio", "category": "Microsoft Tools" },
    { "name": "Tabby.sh", "icon": "", "wingetId": "Eugeny.Tabby", "category": "Utilities" },
    { "name": "Tailscale", "icon": "", "wingetId": "tailscale.tailscale", "category": "Utilities" },
    { "name": "TCNO Account Switcher", "icon": "", "wingetId": "TechNobo.TcNoAccountSwitcher", "category": "Games" },
    { "name": "SysInternals TCPView", "icon": "", "wingetId": "Microsoft.Sysinternals.TCPView", "category": "Microsoft Tools" },
    { "name": "Teams", "icon": "", "wingetId": "Microsoft.Teams", "category": "Communications" },
    { "name": "TeamViewer", "icon": "", "wingetId": "TeamViewer.TeamViewer", "category": "Utilities" },
    { "name": "Telegram", "icon": "", "wingetId": "Telegram.TelegramDesktop", "category": "Communications" },
    { "name": "Unigram", "icon": "", "wingetId": "Telegram.Unigram", "category": "Communications" },
    { "name": "Windows Terminal", "icon": "", "wingetId": "Microsoft.WindowsTerminal", "category": "Microsoft Tools" },
    { "name": "Thonny Python IDE", "icon": "", "wingetId": "AivarAnnamaa.Thonny", "category": "Development" },
    { "name": "Code With Mu (Mu Editor)", "icon": "", "wingetId": "Mu.Mu", "category": "Development" },
    { "name": "Thorium Browser AVX2", "icon": "", "wingetId": "Alex313031.Thorium.AVX2", "category": "Browsers" },
    { "name": "Thunderbird", "icon": "", "wingetId": "Mozilla.Thunderbird", "category": "Communications" },
    { "name": "Betterbird", "icon": "", "wingetId": "Betterbird.Betterbird", "category": "Communications" },
    { "name": "Tidal", "icon": "", "wingetId": "9NNCB5BS59PH", "category": "Multimedia Tools" },
    { "name": "Tor Browser", "icon": "", "wingetId": "TorProject.TorBrowser", "category": "Browsers" },
    { "name": "Total Commander", "icon": "", "wingetId": "Ghisler.TotalCommander", "category": "Utilities" },
    { "name": "TreeSize Free", "icon": "", "wingetId": "JAMSoftware.TreeSize.Free", "category": "Utilities" },
    { "name": "Translucent Taskbar", "icon": "", "wingetId": "9PF4KZ2VN4W9", "category": "Utilities" },
    { "name": "Twinkle Tray", "icon": "", "wingetId": "xanderfrangos.twinkletray", "category": "Utilities" },
    { "name": "Ubisoft Connect", "icon": "", "wingetId": "Ubisoft.Connect", "category": "Games" },
    { "name": "Ungoogled", "icon": "", "wingetId": "eloston.ungoogled-chromium", "category": "Browsers" },
    { "name": "Unity Game Engine", "icon": "", "wingetId": "Unity.UnityHub", "category": "Development" },
    { "name": "Vagrant", "icon": "", "wingetId": "Hashicorp.Vagrant", "category": "Development" },
    { "name": "Visual C++ 2015-2022 32-bit", "icon": "", "wingetId": "Microsoft.VCRedist.2015+.x86", "category": "Microsoft Tools" },
    { "name": "Visual C++ 2015-2022 64-bit", "icon": "", "wingetId": "Microsoft.VCRedist.2015+.x64", "category": "Microsoft Tools" },
    { "name": "Ventoy", "icon": "", "wingetId": "Ventoy.Ventoy", "category": "Pro Tools" },
    { "name": "Vesktop", "icon": "", "wingetId": "Vencord.Vesktop", "category": "Communications" },
    { "name": "Viber", "icon": "", "wingetId": "Viber.Viber", "category": "Communications" },
    { "name": "Videomass", "icon": "", "wingetId": "GianlucaPernigotto.Videomass", "category": "Multimedia Tools" },
    { "name": "Visual Studio 2022", "icon": "", "wingetId": "Microsoft.VisualStudio.2022.Community", "category": "Development" },
    { "name": "Vivaldi", "icon": "", "wingetId": "Vivaldi.Vivaldi", "category": "Browsers" },
    { "name": "VLC (Video Player)", "icon": "", "wingetId": "VideoLAN.VLC", "category": "Multimedia Tools" },
    { "name": "Voicemeeter (Audio)", "icon": "", "wingetId": "VB-Audio.Voicemeeter", "category": "Multimedia Tools" },
    { "name": "Voicemeeter Potato", "icon": "", "wingetId": "VB-Audio.Voicemeeter.Potato", "category": "Multimedia Tools" },
    { "name": "Virtual Desktop Streamer", "icon": "", "wingetId": "VirtualDesktop.Streamer", "category": "Games" },
    { "name": "VS Code", "icon": "", "wingetId": "Microsoft.VisualStudioCode", "category": "Development" },
    { "name": "VS Codium", "icon": "", "wingetId": "VSCodium.VSCodium", "category": "Development" },
    { "name": "Waterfox", "icon": "", "wingetId": "Waterfox.Waterfox", "category": "Browsers" },
    { "name": "Wazuh.", "icon": "", "wingetId": "Wazuh.WazuhAgent", "category": "Utilities" },
    { "name": "Wezterm", "icon": "", "wingetId": "wez.wezterm", "category": "Development" },
    { "name": "Windows PC Health Check", "icon": "", "wingetId": "Microsoft.WindowsPCHealthCheck", "category": "Utilities" },
    { "name": "WindowGrid", "icon": "", "wingetId": "na", "category": "Utilities" },
    { "name": "UniGetUI", "icon": "", "wingetId": "MartiCliment.UniGetUI", "category": "Utilities" },
    { "name": "WinMerge", "icon": "", "wingetId": "WinMerge.WinMerge", "category": "Document" },
    { "name": "WinPaletter", "icon": "", "wingetId": "Abdelrhman-AK.WinPaletter", "category": "Utilities" },
    { "name": "WinRAR", "icon": "", "wingetId": "RARLab.WinRAR", "category": "Utilities" },
    { "name": "WinSCP", "icon": "", "wingetId": "WinSCP.WinSCP", "category": "Pro Tools" },
    { "name": "WireGuard", "icon": "", "wingetId": "WireGuard.WireGuard", "category": "Pro Tools" },
    { "name": "Wireshark", "icon": "", "wingetId": "WiresharkFoundation.Wireshark", "category": "Pro Tools" },
    { "name": "WiseToys", "icon": "", "wingetId": "WiseCleaner.WiseToys", "category": "Utilities" },
    { "name": "TeraCopy", "icon": "", "wingetId": "CodeSector.TeraCopy", "category": "Utilities" },
    { "name": "WizFile", "icon": "", "wingetId": "AntibodySoftware.WizFile", "category": "Utilities" },
    { "name": "WizTree", "icon": "", "wingetId": "AntibodySoftware.WizTree", "category": "Utilities" },
    { "name": "Xtreme Download Manager", "icon": "", "wingetId": "subhra74.XtremeDownloadManager", "category": "Utilities" },
    { "name": "HxD Hex Editor", "icon": "", "wingetId": "MHNexus.HxD", "category": "Utilities" },
    { "name": "XEMU", "icon": "", "wingetId": "xemu-project.xemu", "category": "Games" },
    { "name": "XnView classic", "icon": "", "wingetId": "XnSoft.XnView.Classic", "category": "Utilities" },
    { "name": "Xournal++", "icon": "", "wingetId": "Xournal++.Xournal++", "category": "Document" },
    { "name": "XPipe", "icon": "", "wingetId": "xpipe-io.xpipe", "category": "Pro Tools" },
    { "name": "Yarn", "icon": "", "wingetId": "Yarn.Yarn", "category": "Development" },
    { "name": "Yt-dlp", "icon": "", "wingetId": "yt-dlp.yt-dlp", "category": "Multimedia Tools" },
    { "name": "ZeroTier One", "icon": "", "wingetId": "ZeroTier.ZeroTierOne", "category": "Utilities" },
    { "name": "Zim Desktop Wiki", "icon": "", "wingetId": "Zimwiki.Zim", "category": "Document" },
    { "name": "Znote", "icon": "", "wingetId": "alagrede.znote", "category": "Document" },
    { "name": "Zoom", "icon": "", "wingetId": "Zoom.Zoom", "category": "Communications" },
    { "name": "ZoomIt", "icon": "", "wingetId": "Microsoft.Sysinternals.ZoomIt", "category": "Utilities" },
    { "name": "Zotero", "icon": "", "wingetId": "DigitalScholar.Zotero", "category": "Document" },
    { "name": "Zoxide", "icon": "", "wingetId": "ajeetdsouza.zoxide", "category": "Utilities" },
    { "name": "Zulip", "icon": "", "wingetId": "Zulip.Zulip", "category": "Communications" },
    { "name": "Syncthingtray", "icon": "", "wingetId": "Martchus.syncthingtray", "category": "Utilities" },
    { "name": "Miniconda", "icon": "", "wingetId": "Anaconda.Miniconda3", "category": "Development" },
    { "name": "Pixi", "icon": "", "wingetId": "prefix-dev.pixi", "category": "Development" },
    { "name": "Eclipse Temurin", "icon": "", "wingetId": "EclipseAdoptium.Temurin.21.JDK", "category": "Development" },
    { "name": "Intel-PresentMon", "icon": "", "wingetId": "Intel.PresentMon.Beta", "category": "Utilities" },
    { "name": "Python Version Manager (pyenv-win)", "icon": "", "wingetId": "na", "category": "Development" },
    { "name": "TightVNC", "icon": "", "wingetId": "GlavSoft.TightVNC", "category": "Utilities" },
    { "name": "UltraVNC", "icon": "", "wingetId": "uvncbvba.UltraVnc", "category": "Utilities" },
    { "name": "Windows Firewall Control", "icon": "", "wingetId": "BiniSoft.WindowsFirewallControl", "category": "Utilities" },
    { "name": "VistaSwitcher", "icon": "", "wingetId": "ntwind.VistaSwitcher", "category": "Utilities" },
    { "name": "Windows Auto Dark Mode", "icon": "", "wingetId": "Armin2208.WindowsAutoNightMode", "category": "Utilities" },
    { "name": "Ambie White Noise", "icon": "", "wingetId": "9P07XNM5CHP0", "category": "Utilities" },
    { "name": "Magic Wormhole", "icon": "", "wingetId": "magic-wormhole.magic-wormhole", "category": "Utilities" },
    { "name": "croc", "icon": "", "wingetId": "schollz.croc", "category": "Utilities" },
    { "name": "QGIS", "icon": "", "wingetId": "OSGeo.QGIS", "category": "Multimedia Tools" },
    { "name": "SMPlayer", "icon": "", "wingetId": "SMPlayer.SMPlayer", "category": "Multimedia Tools" },
    { "name": "GlazeWM", "icon": "", "wingetId": "glzr-io.glazewm", "category": "Utilities" },
    { "name": "FanControl", "icon": "", "wingetId": "Rem0o.FanControl", "category": "Utilities" },
    { "name": "Fast Node Manager", "icon": "", "wingetId": "Schniz.fnm", "category": "Development" },
    { "name": "Windhawk", "icon": "", "wingetId": "RamenSoftware.Windhawk", "category": "Utilities" },
    { "name": "ForceAutoHDR", "icon": "", "wingetId": "ForceAutoHDR.7gxycn08", "category": "Utilities" },
    { "name": "JoyToKey", "icon": "", "wingetId": "JTKsoftware.JoyToKey", "category": "Utilities" },
    { "name": "NDI Tools", "icon": "", "wingetId": "NDI.NDITools", "category": "Multimedia Tools" },
    { "name": "Kicad", "icon": "", "wingetId": "KiCad.KiCad", "category": "Multimedia Tools" },
    { "name": "Dropbox", "icon": "", "wingetId": "Dropbox.Dropbox", "category": "Utilities" },
    { "name": "OFGB (Oh Frick Go Back)", "icon": "", "wingetId": "xM4ddy.OFGB", "category": "Utilities" },
    { "name": "PaleMoon", "icon": "", "wingetId": "MoonchildProductions.PaleMoon", "category": "Browsers" },
    { "name": "Shotcut", "icon": "", "wingetId": "Meltytech.Shotcut", "category": "Multimedia Tools" },
    { "name": "Lenovo Legion Toolkit", "icon": "", "wingetId": "BartoszCichecki.LenovoLegionToolkit", "category": "Utilities" },
    { "name": "Pulsar", "icon": "", "wingetId": "Pulsar-Edit.Pulsar", "category": "Development" },
    { "name": "Aegisub", "icon": "", "wingetId": "Aegisub.Aegisub", "category": "Development" },
    { "name": "Subtitle Edit", "icon": "", "wingetId": "Nikse.SubtitleEdit", "category": "Multimedia Tools" },
    { "name": "Fork", "icon": "", "wingetId": "Fork.Fork", "category": "Development" },
    { "name": "Zen Browser", "icon": "", "wingetId": "Zen-Team.Zen-Browser", "category": "Browsers" }
];